### ISSUE TITLE
CNMT Digest

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [AnalogMan151/CDNSP#2]
How exactly is this generated, and why is it not documtented?

**Comment by AnalogMan151** [comment]
Are you talking about this line here?
https://github.com/AnalogMan151/CDNSP/blob/master/CDNSP.py#L477

If so, it's just reading the last 0x20 bytes at the end of the CNMT file as documented here: https://switchbrew.org/wiki/NCA

Nothing is generated so I'm not sure why documentation is needed? Should I comment all read commands with a
```python
# Reading X bytes from Offset Y
```
?

**Comment by ThatNerdyPikachu** [comment]
didn't see that part of switchbrew, sorry

**Comment by AnalogMan151** [comment]
No problem, this is really old by the way, I had planned to rewrite it but new features were added faster than I could rewrite it so I just stopped. This is far from good code.
